version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rapticore-loki-promtail"
s3_prefix = "rapticore-loki-promtail"
region = "us-west-2"
capabilities = "CAPABILITY_NAMED_IAM"
